version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.20.0

    steps:
      - checkout
      - run: npm --prefix ./client install
      - run: npm --prefix ./client run dev
