version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.20.0    

    working_directory: ~/repo    

    steps:
      - checkout      
      - run: npm install
      - run: npm test
      - run: npm run dev
