version: 2
jobs:
  build:
    working_directory: ~/repo/client
    docker:
      - image: circleci/node:10.20.0

    steps:
      - checkout:
          path: ~/repo/client
      - persist_to_workspace:
          root: .
          paths:
            - client
      - run: npm install
      - run: npm run dev
